# Generated by Django 5.0.2 on 2024-02-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantedtree",
            name="tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planted_trees",
                to="tree.tree",
            ),
        ),
    ]
