# Generated by Django 5.0.2 on 2024-02-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0002_alter_account_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="accounts", to="tree.user"
            ),
        ),
    ]
