# Generated by Django 5.0.2 on 2024-02-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0002_alter_plantedtree_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="tree",
            name="image_source",
            field=models.URLField(blank=True, null=True),
        ),
    ]
